title: Loops
description: A learning platform that encourages iterative learning process!
theme: just-the-docs

url: https://vilas10.github.io/loops/

aux_links:
  About: https://vilas10.github.io/loops/
